# Docker-compose for Graylog

rabbit1:
  image: "rabbitmq:3.7-management"
  hostname: "rabbit"
  environment:
    RABBITMQ_ERLANG_COOKIE: "NINJATORABBITERLANGCOOKIE"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "rabbitmq"
  volumes:
    - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
    #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    #- "./autocluster-0.6.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.7.0/plugins/autocluster-0.6.1.ez"
